[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "github-analyzer"
version = "0.1.0"
description = "A tool for analyzing GitHub repositories using tree-sitter"
requires-python = ">=3.9"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "click>=8.0.0",
    "pyyaml>=6.0.1",
    "tree-sitter>=0.20.1",
    # Core languages
    "tree-sitter-python==0.23.6",
    "tree-sitter-javascript==0.23.1",
    "tree-sitter-typescript==0.23.2",
    # Additional languages
    "tree-sitter-java==0.23.5",
    "tree-sitter-cpp==0.23.4",
    "tree-sitter-go==0.23.4",
    "tree-sitter-ruby==0.23.1",
    "tree-sitter-php==0.23.11",
    "tree-sitter-c==0.23.4",
    "tree-sitter-c-sharp==0.23.1",
    "tree-sitter-scala==0.23.4",
    "tree-sitter-kotlin==1.0.1",
    "tree-sitter-lua==0.2.0",
    "tree-sitter-bash==0.23.3",
    "tree-sitter-html==0.23.2",
    "tree-sitter-css==0.23.1",
    "tree-sitter-json==0.24.8",
    "tree-sitter-yaml==0.7.0",
    "tree-sitter-toml==0.7.0",
    "tree-sitter-xml==0.7.0",
    "tree-sitter-markdown==0.3.2",
    "tree-sitter-sql==0.3.7",
    "tree-sitter-arduino==0.23.0",
    "tree-sitter-cuda==0.20.6",
    "tree-sitter-groovy==0.1.2",
    "tree-sitter-matlab==1.0.2",
]

[project.optional-dependencies]
dev = [
    "black>=24.1.0",
    "isort>=5.13.2",
    "mypy>=1.8.0",
    "pylint>=3.0.3",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "pytest-timeout>=2.3.1",
    "pytest-mock>=3.14.0",
]

[project.scripts]
github-analyzer = "GithubAnalyzer.cli:main"

[project.urls]
"Homepage" = "https://github.com/yourusername/GithubAnalyzer"
"Bug Tracker" = "https://github.com/yourusername/GithubAnalyzer/issues"

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true
namespace_packages = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    "tree_sitter.*",
]
ignore_missing_imports = true

[tool.pylint]
max-line-length = 88
disable = [
    "C0111",  # missing-docstring
    "R0903",  # too-few-public-methods
    "C0103",  # invalid-name
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
]
good-names = ["i", "j", "k", "ex", "Run", "_", "fp", "id"]
ignore-paths = ["tests"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q --cov=src/GithubAnalyzer --cov-report=term-missing"
testpaths = [
    "tests/test_parsers/test_tree_sitter.py",
    "tests/test_parsers/test_tree_sitter_advanced.py"
]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
