"""Tree-sitter patterns for language parsing."""

from .common import JS_TS_SHARED_PATTERNS
from .javascript import JS_VARIANT_PATTERNS
from .typescript import TS_PATTERNS
from .python import PYTHON_PATTERNS
from .java import JAVA_PATTERNS
from .cpp import CPP_PATTERNS
from .csharp import CSHARP_PATTERNS
from .go import GO_PATTERNS
from .rust import RUST_PATTERNS
from .ruby import RUBY_PATTERNS
from .php import PHP_PATTERNS
from .swift import SWIFT_PATTERNS
from .kotlin import KOTLIN_PATTERNS
from .scala import SCALA_PATTERNS
from .other import (
    ADA_PATTERNS, HASKELL_PATTERNS, PERL_PATTERNS,
    OBJECTIVEC_PATTERNS, LUA_PATTERNS, GROOVY_PATTERNS,
    RACKET_PATTERNS, CLOJURE_PATTERNS, SQUIRREL_PATTERNS,
    POWERSHELL_PATTERNS
)
from .markup import (
    HTML_PATTERNS, YAML_PATTERNS, TOML_PATTERNS,
    DOCKERFILE_PATTERNS, MARKDOWN_PATTERNS
)

# Export all patterns
__all__ = [
    'JS_TS_SHARED_PATTERNS',
    'JS_VARIANT_PATTERNS',
    'TS_PATTERNS',
    'PYTHON_PATTERNS',
    'JAVA_PATTERNS',
    'CPP_PATTERNS',
    'CSHARP_PATTERNS',
    'GO_PATTERNS',
    'RUST_PATTERNS',
    'RUBY_PATTERNS',
    'PHP_PATTERNS',
    'SWIFT_PATTERNS',
    'KOTLIN_PATTERNS',
    'SCALA_PATTERNS',
    'HTML_PATTERNS',
    'YAML_PATTERNS',
    'TOML_PATTERNS',
    'DOCKERFILE_PATTERNS',
    'MARKDOWN_PATTERNS',
    'ADA_PATTERNS',
    'HASKELL_PATTERNS',
    'PERL_PATTERNS',
    'OBJECTIVEC_PATTERNS',
    'LUA_PATTERNS',
    'GROOVY_PATTERNS',
    'RACKET_PATTERNS',
    'CLOJURE_PATTERNS',
    'SQUIRREL_PATTERNS',
    'POWERSHELL_PATTERNS'
] 